# This file keeps all Constants from BridgeInTech backend

# from OrganizationDAO constants
DEFAULT_PAGE = 1
DEFAULT_ORGANIZATIONS_PER_PAGE = 10
MAX_ORGANIZATIONS_PER_PAGE = 50
DEFAULT_PROGRAMS_PER_PAGE = 10
MAX_PROGRAMS_PER_PAGE = 50
 