name: Run tests

on:
   push:
    branches: [develop]
   pull_request:
    branches: [develop]

jobs:
  build:

    runs-on: Ubuntu-20.04

    env:
      DB_TYPE: postgresql
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_ENDPOINT: localhost:5432 
      DB_TEST_NAME: bit_schema_test
      
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Connect to PostgreSQL
      run: |
        PGPASSWORD=postgres psql -h localhost -c 'CREATE DATABASE bit_schema_test;' -U postgres
        PGPASSWORD=postgres psql -h localhost -c 'CREATE SCHEMA bitschema;' -U postgres -d bit_schema_test
        PGPASSWORD=postgres psql -h localhost -c 'CREATE SCHEMA test_schema;' -U postgres -d bit_schema_test
        PGPASSWORD=postgres psql -h localhost -c 'create SCHEMA test_schema_2;' -U postgres -d bit_schema_test
        PGPASSWORD=postgres psql -h localhost -c '\dn;' -U postgres -d bit_schema_test
        PGPASSWORD=postgres psql -h localhost -c 'show search_path;' -U postgres -d bit_schema_test
        PGPASSWORD=postgres psql -h localhost -c "ALTER DATABASE bit_schema_test SET search_path TO bitschema,public;" -U postgres -d bit_schema_test
        PGPASSWORD=postgres psql -h localhost -c 'show search_path;' -U postgres -d bit_schema_test
      env:
        POSTGRES_HOST: localhost

    - name: Set up python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        python -m unittest discover tests -v
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
 
    #- name: Upload coverage to Codecov
          
